import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const state=JSON.parse(await readFile('/app/data/deployment-check.json','utf8'));
const base='https://145.241.159.235.nip.io';
const auth=await fetch(base+'/api/auth/sign-in',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:state.email,password:state.password})});
assert(auth.ok);
const cookie=auth.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');
const content='OpenAgent persistent attachment verification';
const form=new FormData();
form.set('operations',JSON.stringify({query:'mutation($options:CreateChatMessageInput!){createCopilotMessage(options:$options)}',variables:{options:{sessionId:state.sessionId,content:'Deployment attachment test',blob:null}}}));
form.set('map',JSON.stringify({'0':['variables.options.blob']}));
form.set('0',new Blob([content],{type:'text/plain'}),'deployment-check.txt');
const r=await fetch(base+'/graphql',{method:'POST',headers:{Cookie:cookie,'Apollo-Require-Preflight':'true'},body:form});
const j=await r.json();assert(!j.errors,JSON.stringify(j.errors));
const current=await fetch(base+'/graphql',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify({query:'query { currentUser { id } }'})});
const userId=(await current.json()).data.currentUser.id;
const url=base+'/api/copilot/blob/'+userId+'/'+createHash('sha256').update(content).digest('base64url');
assert.equal(await (await fetch(url,{headers:{Cookie:cookie}})).text(),content);
await writeFile('/app/data/deployment-attachment-check.json',JSON.stringify({url,content}),{mode:0o600});
console.log('public_upload_and_download=PASS');
